name: "CI"

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        debian_version:
          - bullseye
          - bookworm
        arch:
          - linux/386
          - linux/amd64
          - linux/arm/v5
          - linux/arm/v7
          - linux/arm64/v8
          - linux/mips64le
          - linux/ppc64le
          - linux/s390x
        pg_major:
          - 13
          - 14
          - 15
          - 16
          - 17
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Determine what should be built
        run: |
          if docker manifest inspect "debian:${DEBIAN_VERSION}" | grep -q "${ARCH}"; then
            echo "Platform ${ARCH} is supported by debian:${DEBIAN_VERSION}, proceeding with build check"
            docker run --rm -v `pwd`:/build -e PG_MAJOR=${PG_MAJOR} --platform=${ARCH} "debian:${DEBIAN_VERSION}" /build/check_if_build_needed.sh
          else
            echo "Platform ${ARCH} is NOT supported by debian:${DEBIAN_VERSION}, skipping build"
            touch should_build_ver
          fi

          if [ -s should_build_ver ]; then
            echo "======================== SUMMARY ========================"
            echo "We should build these package versions for arch ${ARCH}"
            cat should_build_ver
            echo "========================================================="
          fi
        env:
          DEBIAN_VERSION: ${{ matrix.debian_version }}
          ARCH: ${{ matrix.arch }}
          PG_MAJOR: ${{ matrix.pg_major }}
      - name: Push base packages if exists
        run: |
          find -name '*.deb' -print0 | xargs -r -0 -I'{}' curl -sF package=@'{}' https://${FURY_PUSH_TOKEN}@push.fury.io/abcfy2/
          rm -f *.deb
        env:
          FURY_PUSH_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
      - name: Build dev packages if needed
        run: |
          if [ -s should_build_ver ]; then
            while read pg_version; do
              docker run --rm -v `pwd`:/build -e PG_MAJOR=${PG_MAJOR} -e PG_VERSION=${pg_version} --platform=${ARCH} "${IMAGE_ID}" /build/build.sh
            done < should_build_ver
          fi
        env:
          ARCH: ${{ matrix.arch }}
          PG_MAJOR: ${{ matrix.pg_major }}
          IMAGE_ID: debian:${{ matrix.debian_version }}
      - name: Push dev packages if exists
        run: |
          find -name '*.deb' -print0 | xargs -r -0 -I'{}' curl -sF package=@'{}' https://${FURY_PUSH_TOKEN}@push.fury.io/abcfy2/
          rm -f *.deb
        env:
          FURY_PUSH_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
